# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load
ZSH_THEME="agnoster-wsl"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Which plugins would you like to load?
# Add wisely, as too many plugins slow down shell startup.
plugins=(
    git
    timer
)

### plugin timer configs
# number of decimal places (default `1`)
export TIMER_PRECISION=2
# display format (default `'/%d'`)
export TIMER_FORMAT='[%d]'
# minimum execution time that causes the timer to be shown (default `0`)
export TIMER_THRESHOLD=0.5

source $ZSH/oh-my-zsh.sh

## GPG stuff
export GPG_TTY=$(tty)

# User configuration
if [ -f $HOME/.shell_aliases ]; then
  source $HOME/.shell_aliases
fi

# Add golang to PATH
export PATH=$PATH:/usr/local/go/bin

# set shell history do ignore duplicate commands
export HISTCONTROL=ignoreboth:erasedups

# lets files beginning with a . be matched without explicitly specifying the dot.
setopt GLOB_DOTS

# share commands between terminal instances or not
unsetopt SHARE_HISTORY
#setopt SHARE_HISTORY

# toggle kubectl prompt function
function kubeprompt(){
	if [[ $KUBE_PROMPT ]]; then
		unset KUBE_PROMPT
	else
		export KUBE_PROMPT=true
	fi
}